// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json",
    "text/html"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "title": "VP API",
    "version": "0.1.0"
  },
  "paths": {
    "/_livenessProbe": {
      "get": {
        "description": "Liveness Probe",
        "produces": [
          "application/json"
        ],
        "tags": [
          "health"
        ],
        "summary": "Liveness Probe",
        "operationId": "getLivenessProbe",
        "responses": {
          "200": {
            "description": "Successful Response",
            "schema": {
              "$ref": "#/definitions/LivenessProbe"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/_readinessProbe": {
      "get": {
        "description": "Readiness Probe",
        "produces": [
          "application/json"
        ],
        "tags": [
          "health"
        ],
        "summary": "Readiness Probe",
        "operationId": "getReadinessProbe",
        "responses": {
          "200": {
            "description": "Successful Response"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/app-codes": {
      "get": {
        "description": "Get list of application codes",
        "produces": [
          "application/json"
        ],
        "tags": [
          "general"
        ],
        "summary": "Get List of Application Codes",
        "operationId": "getAppCodes",
        "responses": {
          "200": {
            "description": "Successful Response",
            "schema": {
              "$ref": "#/definitions/GetAppMessagesResponse"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      }
    },
    "/app/update/{version}": {
      "get": {
        "produces": [
          "application/octet-stream"
        ],
        "tags": [
          "general"
        ],
        "parameters": [
          {
            "$ref": "#/parameters/Version"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "schema": {
              "type": "string",
              "format": "binary"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      }
    },
    "/ping": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "general"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PingMessage"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "schema": {
              "$ref": "#/definitions/PostPingResponse"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      }
    },
    "/proxy/message": {
      "post": {
        "tags": [
          "general"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PostProxyMessageRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "schema": {
              "$ref": "#/definitions/PostProxyMessagesResponse"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      }
    },
    "/push": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "general"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PostMessageRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "schema": {
              "$ref": "#/definitions/PostMessageResponse"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      }
    },
    "/sms": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "general"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PostMessageRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "schema": {
              "$ref": "#/definitions/PostMessageResponse"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AppMessage": {
      "type": "object",
      "title": "AppMessage",
      "required": [
        "message",
        "code",
        "attributes"
      ],
      "properties": {
        "attributes": {
          "description": "attributes",
          "type": "array",
          "items": {
            "type": "string"
          },
          "x-nullable": false
        },
        "code": {
          "type": "string",
          "title": "Code",
          "x-nullable": false
        },
        "message": {
          "type": "string",
          "title": "Message",
          "x-nullable": false
        }
      }
    },
    "ErrorMessage": {
      "type": "object",
      "title": "ErrorMessage",
      "required": [
        "message"
      ],
      "properties": {
        "attributes": {
          "description": "attributes",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "x-nullable": false
        },
        "code": {
          "type": "string",
          "title": "Code",
          "x-nullable": false
        },
        "message": {
          "type": "string",
          "title": "Message",
          "x-nullable": false
        }
      }
    },
    "GetAppMessagesResponse": {
      "type": "array",
      "title": "GetAppCodesResponse",
      "items": {
        "$ref": "#/definitions/AppMessage"
      }
    },
    "LivenessProbe": {
      "type": "object",
      "title": "LivenessProbe",
      "required": [
        "tag"
      ],
      "properties": {
        "components": {
          "type": "array",
          "title": "LivenessProbeComponents",
          "items": {
            "$ref": "#/definitions/LivenessProbeComponent"
          }
        },
        "tag": {
          "type": "string",
          "title": "Tag",
          "x-nullable": false
        }
      }
    },
    "LivenessProbeComponent": {
      "type": "object",
      "title": "LivenessProbeComponent",
      "required": [
        "name",
        "status"
      ],
      "properties": {
        "name": {
          "type": "string",
          "title": "Name",
          "x-nullable": false
        },
        "status": {
          "type": "boolean",
          "title": "Status",
          "x-nullable": false
        }
      }
    },
    "MessageRequest": {
      "type": "object",
      "title": "MessageResponse",
      "required": [
        "id",
        "from",
        "message",
        "datetime",
        "password"
      ],
      "properties": {
        "datetime": {
          "type": "number",
          "title": "Date",
          "x-nullable": false
        },
        "from": {
          "type": "string",
          "title": "From",
          "x-nullable": false
        },
        "id": {
          "type": "string",
          "title": "Device ID",
          "x-nulable": false
        },
        "message": {
          "type": "string",
          "title": "Message",
          "x-nullable": false
        },
        "password": {
          "type": "string",
          "title": "password",
          "x-nullable": false
        }
      }
    },
    "PingMessage": {
      "type": "object",
      "title": "PingMessage",
      "required": [
        "id",
        "password"
      ],
      "properties": {
        "id": {
          "type": "string",
          "title": "ID",
          "x-nullable": false
        },
        "password": {
          "type": "string",
          "title": "password",
          "x-nullable": false
        }
      }
    },
    "PostMessageRequest": {
      "type": "object",
      "title": "PostMessageRequest",
      "$ref": "#/definitions/MessageRequest"
    },
    "PostMessageResponse": {
      "type": "object",
      "title": "PostMessageResponse",
      "$ref": "#/definitions/SuccessResponse"
    },
    "PostPingResponse": {
      "type": "object",
      "title": "PostPingResponse",
      "$ref": "#/definitions/SuccessResponse"
    },
    "PostProxyMessageRequest": {
      "type": "object",
      "title": "PostMessageRequest",
      "$ref": "#/definitions/ProxyMessageRequest"
    },
    "PostProxyMessagesResponse": {
      "type": "object",
      "title": "GetAppCodesResponse",
      "$ref": "#/definitions/ProxySuccessResponse"
    },
    "ProxyMessageRequest": {
      "type": "object",
      "title": "ProxyMessageRequest",
      "required": [
        "id",
        "action",
        "address",
        "body",
        "date"
      ],
      "properties": {
        "action": {
          "type": "string",
          "title": "Action (SMS or PUSH)",
          "x-nullable": false
        },
        "address": {
          "type": "string",
          "title": "From",
          "x-nullable": false
        },
        "body": {
          "type": "string",
          "title": "Message",
          "x-nullable": false
        },
        "date": {
          "type": "string",
          "title": "Date",
          "x-nullable": false
        },
        "id": {
          "type": "string",
          "title": "Device ID",
          "x-nulable": false
        }
      }
    },
    "ProxySuccessResponse": {
      "type": "object",
      "title": "PingResponse",
      "required": [
        "result"
      ],
      "properties": {
        "result": {
          "type": "number",
          "title": "Result",
          "x-nullable": false
        }
      }
    },
    "SuccessResponse": {
      "type": "object",
      "title": "PingResponse",
      "required": [
        "success"
      ],
      "properties": {
        "success": {
          "type": "boolean",
          "title": "Success",
          "x-nullable": false
        }
      }
    }
  },
  "parameters": {
    "Version": {
      "type": "string",
      "x-nullable": false,
      "description": "Version apk",
      "name": "version",
      "in": "path",
      "required": true
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json",
    "text/html"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "title": "VP API",
    "version": "0.1.0"
  },
  "paths": {
    "/_livenessProbe": {
      "get": {
        "description": "Liveness Probe",
        "produces": [
          "application/json"
        ],
        "tags": [
          "health"
        ],
        "summary": "Liveness Probe",
        "operationId": "getLivenessProbe",
        "responses": {
          "200": {
            "description": "Successful Response",
            "schema": {
              "$ref": "#/definitions/LivenessProbe"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/_readinessProbe": {
      "get": {
        "description": "Readiness Probe",
        "produces": [
          "application/json"
        ],
        "tags": [
          "health"
        ],
        "summary": "Readiness Probe",
        "operationId": "getReadinessProbe",
        "responses": {
          "200": {
            "description": "Successful Response"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/app-codes": {
      "get": {
        "description": "Get list of application codes",
        "produces": [
          "application/json"
        ],
        "tags": [
          "general"
        ],
        "summary": "Get List of Application Codes",
        "operationId": "getAppCodes",
        "responses": {
          "200": {
            "description": "Successful Response",
            "schema": {
              "$ref": "#/definitions/GetAppMessagesResponse"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      }
    },
    "/app/update/{version}": {
      "get": {
        "produces": [
          "application/octet-stream"
        ],
        "tags": [
          "general"
        ],
        "parameters": [
          {
            "type": "string",
            "x-nullable": false,
            "description": "Version apk",
            "name": "version",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "schema": {
              "type": "string",
              "format": "binary"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      }
    },
    "/ping": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "general"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PingMessage"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "schema": {
              "$ref": "#/definitions/PostPingResponse"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      }
    },
    "/proxy/message": {
      "post": {
        "tags": [
          "general"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PostProxyMessageRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "schema": {
              "$ref": "#/definitions/PostProxyMessagesResponse"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      }
    },
    "/push": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "general"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PostMessageRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "schema": {
              "$ref": "#/definitions/PostMessageResponse"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      }
    },
    "/sms": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "general"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PostMessageRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "schema": {
              "$ref": "#/definitions/PostMessageResponse"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AppMessage": {
      "type": "object",
      "title": "AppMessage",
      "required": [
        "message",
        "code",
        "attributes"
      ],
      "properties": {
        "attributes": {
          "description": "attributes",
          "type": "array",
          "items": {
            "type": "string"
          },
          "x-nullable": false
        },
        "code": {
          "type": "string",
          "title": "Code",
          "x-nullable": false
        },
        "message": {
          "type": "string",
          "title": "Message",
          "x-nullable": false
        }
      }
    },
    "ErrorMessage": {
      "type": "object",
      "title": "ErrorMessage",
      "required": [
        "message"
      ],
      "properties": {
        "attributes": {
          "description": "attributes",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "x-nullable": false
        },
        "code": {
          "type": "string",
          "title": "Code",
          "x-nullable": false
        },
        "message": {
          "type": "string",
          "title": "Message",
          "x-nullable": false
        }
      }
    },
    "GetAppMessagesResponse": {
      "type": "array",
      "title": "GetAppCodesResponse",
      "items": {
        "$ref": "#/definitions/AppMessage"
      }
    },
    "LivenessProbe": {
      "type": "object",
      "title": "LivenessProbe",
      "required": [
        "tag"
      ],
      "properties": {
        "components": {
          "type": "array",
          "title": "LivenessProbeComponents",
          "items": {
            "$ref": "#/definitions/LivenessProbeComponent"
          }
        },
        "tag": {
          "type": "string",
          "title": "Tag",
          "x-nullable": false
        }
      }
    },
    "LivenessProbeComponent": {
      "type": "object",
      "title": "LivenessProbeComponent",
      "required": [
        "name",
        "status"
      ],
      "properties": {
        "name": {
          "type": "string",
          "title": "Name",
          "x-nullable": false
        },
        "status": {
          "type": "boolean",
          "title": "Status",
          "x-nullable": false
        }
      }
    },
    "MessageRequest": {
      "type": "object",
      "title": "MessageResponse",
      "required": [
        "id",
        "from",
        "message",
        "datetime",
        "password"
      ],
      "properties": {
        "datetime": {
          "type": "number",
          "title": "Date",
          "x-nullable": false
        },
        "from": {
          "type": "string",
          "title": "From",
          "x-nullable": false
        },
        "id": {
          "type": "string",
          "title": "Device ID",
          "x-nulable": false
        },
        "message": {
          "type": "string",
          "title": "Message",
          "x-nullable": false
        },
        "password": {
          "type": "string",
          "title": "password",
          "x-nullable": false
        }
      }
    },
    "PingMessage": {
      "type": "object",
      "title": "PingMessage",
      "required": [
        "id",
        "password"
      ],
      "properties": {
        "id": {
          "type": "string",
          "title": "ID",
          "x-nullable": false
        },
        "password": {
          "type": "string",
          "title": "password",
          "x-nullable": false
        }
      }
    },
    "PostMessageRequest": {
      "type": "object",
      "title": "PostMessageRequest",
      "$ref": "#/definitions/MessageRequest"
    },
    "PostMessageResponse": {
      "type": "object",
      "title": "PostMessageResponse",
      "$ref": "#/definitions/SuccessResponse"
    },
    "PostPingResponse": {
      "type": "object",
      "title": "PostPingResponse",
      "$ref": "#/definitions/SuccessResponse"
    },
    "PostProxyMessageRequest": {
      "type": "object",
      "title": "PostMessageRequest",
      "$ref": "#/definitions/ProxyMessageRequest"
    },
    "PostProxyMessagesResponse": {
      "type": "object",
      "title": "GetAppCodesResponse",
      "$ref": "#/definitions/ProxySuccessResponse"
    },
    "ProxyMessageRequest": {
      "type": "object",
      "title": "ProxyMessageRequest",
      "required": [
        "id",
        "action",
        "address",
        "body",
        "date"
      ],
      "properties": {
        "action": {
          "type": "string",
          "title": "Action (SMS or PUSH)",
          "x-nullable": false
        },
        "address": {
          "type": "string",
          "title": "From",
          "x-nullable": false
        },
        "body": {
          "type": "string",
          "title": "Message",
          "x-nullable": false
        },
        "date": {
          "type": "string",
          "title": "Date",
          "x-nullable": false
        },
        "id": {
          "type": "string",
          "title": "Device ID",
          "x-nulable": false
        }
      }
    },
    "ProxySuccessResponse": {
      "type": "object",
      "title": "PingResponse",
      "required": [
        "result"
      ],
      "properties": {
        "result": {
          "type": "number",
          "title": "Result",
          "x-nullable": false
        }
      }
    },
    "SuccessResponse": {
      "type": "object",
      "title": "PingResponse",
      "required": [
        "success"
      ],
      "properties": {
        "success": {
          "type": "boolean",
          "title": "Success",
          "x-nullable": false
        }
      }
    }
  },
  "parameters": {
    "Version": {
      "type": "string",
      "x-nullable": false,
      "description": "Version apk",
      "name": "version",
      "in": "path",
      "required": true
    }
  }
}`))
}
