FROM golang:1.19-alpine AS builder

WORKDIR /go/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /go/bin/stat ./cmd/stat/main.go

FROM alpine:latest

RUN apk add --no-cache \
    curl \
    && rm -f /var/cache/apk/* \
    && rm -rf /root/.cache

WORKDIR /app

COPY --from=builder /go/bin/stat .

EXPOSE 80

CMD [ "./stat" ]
