FROM golang:1.17-alpine AS builder

WORKDIR /go/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /go/bin/wallet ./cmd/wallet/main.go

FROM alpine:latest

RUN apk add --no-cache \
    curl \
    && rm -f /var/cache/apk/* \
    && rm -rf /root/.cache

WORKDIR /app

COPY tools/migrations migrations/

COPY --from=builder /go/bin/wallet .

EXPOSE 9000

CMD [ "./wallet" ]
