version: "3.9"

services:
  ### services (sorted by port)
  vp:
    build:
      context: build/service
    depends_on:
      - backend-db
    volumes:
      - .:$PWD
    working_dir: $PWD
    command: /bin/bash -c "go mod download && ls -la cmd/vp && cd cmd/vp && pwd && go run main.go"
    env_file:
      - .env
    environment:
      - DEBUG=1
    healthcheck:
      test:
        [
            "CMD",
            "curl",
            "-f",
            "http://localhost:$VP_SERVICE_PORT/_livenessProbe",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - $VP_SERVICE_PORT:$VP_SERVICE_PORT
  backend-db:
    image: mongo:latest
    ports:
      - "27017:27017"



volumes:
  esdata:
    driver: local