// Code generated by go-swagger; DO NOT EDIT.

package general

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAppUpdateParams creates a new GetAppUpdateParams object
// with the default values initialized.
func NewGetAppUpdateParams() *GetAppUpdateParams {

	return &GetAppUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAppUpdateParamsWithTimeout creates a new GetAppUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAppUpdateParamsWithTimeout(timeout time.Duration) *GetAppUpdateParams {

	return &GetAppUpdateParams{

		timeout: timeout,
	}
}

// NewGetAppUpdateParamsWithContext creates a new GetAppUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAppUpdateParamsWithContext(ctx context.Context) *GetAppUpdateParams {

	return &GetAppUpdateParams{

		Context: ctx,
	}
}

// NewGetAppUpdateParamsWithHTTPClient creates a new GetAppUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAppUpdateParamsWithHTTPClient(client *http.Client) *GetAppUpdateParams {

	return &GetAppUpdateParams{
		HTTPClient: client,
	}
}

/*GetAppUpdateParams contains all the parameters to send to the API endpoint
for the get app update operation typically these are written to a http.Request
*/
type GetAppUpdateParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get app update params
func (o *GetAppUpdateParams) WithTimeout(timeout time.Duration) *GetAppUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get app update params
func (o *GetAppUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get app update params
func (o *GetAppUpdateParams) WithContext(ctx context.Context) *GetAppUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get app update params
func (o *GetAppUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get app update params
func (o *GetAppUpdateParams) WithHTTPClient(client *http.Client) *GetAppUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get app update params
func (o *GetAppUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAppUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
