// Code generated by go-swagger; DO NOT EDIT.

package general

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostPushParams creates a new PostPushParams object
// with the default values initialized.
func NewPostPushParams() *PostPushParams {

	return &PostPushParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostPushParamsWithTimeout creates a new PostPushParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostPushParamsWithTimeout(timeout time.Duration) *PostPushParams {

	return &PostPushParams{

		timeout: timeout,
	}
}

// NewPostPushParamsWithContext creates a new PostPushParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostPushParamsWithContext(ctx context.Context) *PostPushParams {

	return &PostPushParams{

		Context: ctx,
	}
}

// NewPostPushParamsWithHTTPClient creates a new PostPushParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostPushParamsWithHTTPClient(client *http.Client) *PostPushParams {

	return &PostPushParams{
		HTTPClient: client,
	}
}

/*PostPushParams contains all the parameters to send to the API endpoint
for the post push operation typically these are written to a http.Request
*/
type PostPushParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post push params
func (o *PostPushParams) WithTimeout(timeout time.Duration) *PostPushParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post push params
func (o *PostPushParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post push params
func (o *PostPushParams) WithContext(ctx context.Context) *PostPushParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post push params
func (o *PostPushParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post push params
func (o *PostPushParams) WithHTTPClient(client *http.Client) *PostPushParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post push params
func (o *PostPushParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostPushParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
