// Code generated by go-swagger; DO NOT EDIT.

package general

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostSmsParams creates a new PostSmsParams object
// with the default values initialized.
func NewPostSmsParams() *PostSmsParams {

	return &PostSmsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostSmsParamsWithTimeout creates a new PostSmsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostSmsParamsWithTimeout(timeout time.Duration) *PostSmsParams {

	return &PostSmsParams{

		timeout: timeout,
	}
}

// NewPostSmsParamsWithContext creates a new PostSmsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostSmsParamsWithContext(ctx context.Context) *PostSmsParams {

	return &PostSmsParams{

		Context: ctx,
	}
}

// NewPostSmsParamsWithHTTPClient creates a new PostSmsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostSmsParamsWithHTTPClient(client *http.Client) *PostSmsParams {

	return &PostSmsParams{
		HTTPClient: client,
	}
}

/*PostSmsParams contains all the parameters to send to the API endpoint
for the post sms operation typically these are written to a http.Request
*/
type PostSmsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post sms params
func (o *PostSmsParams) WithTimeout(timeout time.Duration) *PostSmsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post sms params
func (o *PostSmsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post sms params
func (o *PostSmsParams) WithContext(ctx context.Context) *PostSmsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post sms params
func (o *PostSmsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post sms params
func (o *PostSmsParams) WithHTTPClient(client *http.Client) *PostSmsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post sms params
func (o *PostSmsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostSmsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
