// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MessageRequest MessageResponse
//
// swagger:model MessageRequest
type MessageRequest struct {

	// Date
	// Required: true
	Datetime float64 `json:"datetime"`

	// From
	// Required: true
	From string `json:"from"`

	// Device ID
	// Required: true
	ID *string `json:"id"`

	// Message
	// Required: true
	Message string `json:"message"`

	// password
	// Required: true
	Password string `json:"password"`
}

// Validate validates this message request
func (m *MessageRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDatetime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFrom(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MessageRequest) validateDatetime(formats strfmt.Registry) error {

	if err := validate.Required("datetime", "body", float64(m.Datetime)); err != nil {
		return err
	}

	return nil
}

func (m *MessageRequest) validateFrom(formats strfmt.Registry) error {

	if err := validate.RequiredString("from", "body", m.From); err != nil {
		return err
	}

	return nil
}

func (m *MessageRequest) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *MessageRequest) validateMessage(formats strfmt.Registry) error {

	if err := validate.RequiredString("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

func (m *MessageRequest) validatePassword(formats strfmt.Registry) error {

	if err := validate.RequiredString("password", "body", m.Password); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this message request based on context it is used
func (m *MessageRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MessageRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MessageRequest) UnmarshalBinary(b []byte) error {
	var res MessageRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
