// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostProxyMessageRequest PostMessageRequest
//
// swagger:model PostProxyMessageRequest
type PostProxyMessageRequest struct {
	ProxyMessageRequest
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *PostProxyMessageRequest) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ProxyMessageRequest
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ProxyMessageRequest = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m PostProxyMessageRequest) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.ProxyMessageRequest)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post proxy message request
func (m *PostProxyMessageRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this post proxy message request based on the context it is used
func (m *PostProxyMessageRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ProxyMessageRequest
	if err := m.ProxyMessageRequest.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
