// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProxySuccessResponse PingResponse
//
// swagger:model ProxySuccessResponse
type ProxySuccessResponse struct {

	// Result
	// Required: true
	Result float64 `json:"result"`
}

// Validate validates this proxy success response
func (m *ProxySuccessResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProxySuccessResponse) validateResult(formats strfmt.Registry) error {

	if err := validate.Required("result", "body", float64(m.Result)); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this proxy success response based on context it is used
func (m *ProxySuccessResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProxySuccessResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProxySuccessResponse) UnmarshalBinary(b []byte) error {
	var res ProxySuccessResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
