// Code generated by go-swagger; DO NOT EDIT.

package vp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LivenessProbeComponent LivenessProbeComponent
//
// swagger:model LivenessProbeComponent
type LivenessProbeComponent struct {

	// Name
	// Required: true
	Name string `json:"name"`

	// Status
	// Required: true
	Status bool `json:"status"`
}

// Validate validates this liveness probe component
func (m *LivenessProbeComponent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LivenessProbeComponent) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *LivenessProbeComponent) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", bool(m.Status)); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this liveness probe component based on context it is used
func (m *LivenessProbeComponent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LivenessProbeComponent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LivenessProbeComponent) UnmarshalBinary(b []byte) error {
	var res LivenessProbeComponent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
