// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetReadinessProbeParams creates a new GetReadinessProbeParams object
// with the default values initialized.
func NewGetReadinessProbeParams() *GetReadinessProbeParams {

	return &GetReadinessProbeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetReadinessProbeParamsWithTimeout creates a new GetReadinessProbeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetReadinessProbeParamsWithTimeout(timeout time.Duration) *GetReadinessProbeParams {

	return &GetReadinessProbeParams{

		timeout: timeout,
	}
}

// NewGetReadinessProbeParamsWithContext creates a new GetReadinessProbeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetReadinessProbeParamsWithContext(ctx context.Context) *GetReadinessProbeParams {

	return &GetReadinessProbeParams{

		Context: ctx,
	}
}

// NewGetReadinessProbeParamsWithHTTPClient creates a new GetReadinessProbeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetReadinessProbeParamsWithHTTPClient(client *http.Client) *GetReadinessProbeParams {

	return &GetReadinessProbeParams{
		HTTPClient: client,
	}
}

/*GetReadinessProbeParams contains all the parameters to send to the API endpoint
for the get readiness probe operation typically these are written to a http.Request
*/
type GetReadinessProbeParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get readiness probe params
func (o *GetReadinessProbeParams) WithTimeout(timeout time.Duration) *GetReadinessProbeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get readiness probe params
func (o *GetReadinessProbeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get readiness probe params
func (o *GetReadinessProbeParams) WithContext(ctx context.Context) *GetReadinessProbeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get readiness probe params
func (o *GetReadinessProbeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get readiness probe params
func (o *GetReadinessProbeParams) WithHTTPClient(client *http.Client) *GetReadinessProbeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get readiness probe params
func (o *GetReadinessProbeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetReadinessProbeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
