// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io/ioutil"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetReadinessProbeReader is a Reader for the GetReadinessProbe structure.
type GetReadinessProbeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetReadinessProbeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetReadinessProbeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetReadinessProbeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		data, err := ioutil.ReadAll(response.Body())
		if err != nil {
			return nil, err
		}

		return nil, fmt.Errorf("Requested GET /_readinessProbe returns an error %d: %s", response.Code(), string(data))
	}
}

// NewGetReadinessProbeOK creates a GetReadinessProbeOK with default headers values
func NewGetReadinessProbeOK() *GetReadinessProbeOK {
	return &GetReadinessProbeOK{}
}

/*GetReadinessProbeOK handles this case with default header values.

Successful Response
*/
type GetReadinessProbeOK struct {
}

func (o *GetReadinessProbeOK) Error() string {
	return fmt.Sprintf("[GET /_readinessProbe][%d] getReadinessProbeOK ", 200)
}

func (o *GetReadinessProbeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetReadinessProbeInternalServerError creates a GetReadinessProbeInternalServerError with default headers values
func NewGetReadinessProbeInternalServerError() *GetReadinessProbeInternalServerError {
	return &GetReadinessProbeInternalServerError{}
}

/*GetReadinessProbeInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetReadinessProbeInternalServerError struct {
}

func (o *GetReadinessProbeInternalServerError) Error() string {
	return fmt.Sprintf("[GET /_readinessProbe][%d] getReadinessProbeInternalServerError ", 500)
}

func (o *GetReadinessProbeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
