// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"reflect"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new health API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for health API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetLivenessProbe(params *GetLivenessProbeParams) (*GetLivenessProbeOK, *GetLivenessProbeInternalServerError, error)

	GetReadinessProbe(params *GetReadinessProbeParams) (*GetReadinessProbeOK, *GetReadinessProbeInternalServerError, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetLivenessProbe livenesses probe

  Liveness Probe
*/
func (a *Client) GetLivenessProbe(params *GetLivenessProbeParams) (*GetLivenessProbeOK, *GetLivenessProbeInternalServerError, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetLivenessProbeParams()
	}

	if params.Context == nil {
		params.Context = context.Background()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getLivenessProbe",
		Method:             "GET",
		PathPattern:        "/_livenessProbe",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetLivenessProbeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, err
	}

	switch v := result.(type) {

	case *GetLivenessProbeOK:
		return v, nil, nil
	case *GetLivenessProbeInternalServerError:
		return nil, v, nil
	default:
		return nil, nil, fmt.Errorf("Unexpected Type %v", reflect.TypeOf(v))
	}
}

/*
  GetReadinessProbe readinesses probe

  Readiness Probe
*/
func (a *Client) GetReadinessProbe(params *GetReadinessProbeParams) (*GetReadinessProbeOK, *GetReadinessProbeInternalServerError, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetReadinessProbeParams()
	}

	if params.Context == nil {
		params.Context = context.Background()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getReadinessProbe",
		Method:             "GET",
		PathPattern:        "/_readinessProbe",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetReadinessProbeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, err
	}

	switch v := result.(type) {

	case *GetReadinessProbeOK:
		return v, nil, nil
	case *GetReadinessProbeInternalServerError:
		return nil, v, nil
	default:
		return nil, nil, fmt.Errorf("Unexpected Type %v", reflect.TypeOf(v))
	}
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
