// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/sirupsen/logrus"

	"github.com/lifebackend/vp/internal/app/vp/server/models"
)

// GetLivenessProbeOKCode is the HTTP code returned for type GetLivenessProbeOK
const GetLivenessProbeOKCode int = 200

/*GetLivenessProbeOK Successful Response

swagger:response getLivenessProbeOK
*/
type GetLivenessProbeOK struct {

	/*
	  In: Body
	*/
	Payload *models.LivenessProbe `json:"body,omitempty"`
}

// NewGetLivenessProbeOKFunc is a type the create the response func
type NewGetLivenessProbeOKFunc func() *GetLivenessProbeOK

// NewGetLivenessProbeOK creates GetLivenessProbeOK with default headers values
func NewGetLivenessProbeOK() *GetLivenessProbeOK {

	return &GetLivenessProbeOK{}
}

// WithPayload adds the payload to the get liveness probe o k response
func (o *GetLivenessProbeOK) WithPayload(payload *models.LivenessProbe) *GetLivenessProbeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get liveness probe o k response
func (o *GetLivenessProbeOK) SetPayload(payload *models.LivenessProbe) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLivenessProbeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			logrus.Panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetLivenessProbeInternalServerErrorCode is the HTTP code returned for type GetLivenessProbeInternalServerError
const GetLivenessProbeInternalServerErrorCode int = 500

/*GetLivenessProbeInternalServerError Internal Server Error

swagger:response getLivenessProbeInternalServerError
*/
type GetLivenessProbeInternalServerError struct {
}

// NewGetLivenessProbeInternalServerErrorFunc is a type the create the response func
type NewGetLivenessProbeInternalServerErrorFunc func() *GetLivenessProbeInternalServerError

// NewGetLivenessProbeInternalServerError creates GetLivenessProbeInternalServerError with default headers values
func NewGetLivenessProbeInternalServerError() *GetLivenessProbeInternalServerError {

	return &GetLivenessProbeInternalServerError{}
}

// WriteResponse to the client
func (o *GetLivenessProbeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
