// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetReadinessProbeOKCode is the HTTP code returned for type GetReadinessProbeOK
const GetReadinessProbeOKCode int = 200

/*GetReadinessProbeOK Successful Response

swagger:response getReadinessProbeOK
*/
type GetReadinessProbeOK struct {
}

// NewGetReadinessProbeOKFunc is a type the create the response func
type NewGetReadinessProbeOKFunc func() *GetReadinessProbeOK

// NewGetReadinessProbeOK creates GetReadinessProbeOK with default headers values
func NewGetReadinessProbeOK() *GetReadinessProbeOK {

	return &GetReadinessProbeOK{}
}

// WriteResponse to the client
func (o *GetReadinessProbeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetReadinessProbeInternalServerErrorCode is the HTTP code returned for type GetReadinessProbeInternalServerError
const GetReadinessProbeInternalServerErrorCode int = 500

/*GetReadinessProbeInternalServerError Internal Server Error

swagger:response getReadinessProbeInternalServerError
*/
type GetReadinessProbeInternalServerError struct {
}

// NewGetReadinessProbeInternalServerErrorFunc is a type the create the response func
type NewGetReadinessProbeInternalServerErrorFunc func() *GetReadinessProbeInternalServerError

// NewGetReadinessProbeInternalServerError creates GetReadinessProbeInternalServerError with default headers values
func NewGetReadinessProbeInternalServerError() *GetReadinessProbeInternalServerError {

	return &GetReadinessProbeInternalServerError{}
}

// WriteResponse to the client
func (o *GetReadinessProbeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
