//	Do not edit this file. This file was auto generated
//	All the changes will be overwritten by the "make generate-handler-declarations" command

package handlers

import (
	"github.com/lifebackend/vp/internal/app/wallet/server/restapi/operations"
	"github.com/lifebackend/vp/internal/app/wallet/server/restapi/operations/general"
	"github.com/lifebackend/vp/internal/app/wallet/server/restapi/operations/health"
)

func AddDefaultHandlers(api *operations.WalletAPI, h *Handlers) {
	// default handle functions
	api.GeneralGetAppCodesHandler = general.GetAppCodesHandlerFunc(h.GeneralGetAppCodesHandler)
	api.HealthGetLivenessProbeHandler = health.GetLivenessProbeHandlerFunc(h.HealthGetLivenessProbeHandler)
	api.HealthGetReadinessProbeHandler = health.GetReadinessProbeHandlerFunc(h.HealthGetReadinessProbeHandler)

}
