// Code generated by go-swagger; DO NOT EDIT.

package general

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/lifebackend/vp/internal/vperror"
	"github.com/sirupsen/logrus"

	"github.com/lifebackend/vp/internal/app/vp/server/models"
)

// GetAppCodesOKCode is the HTTP code returned for type GetAppCodesOK
const GetAppCodesOKCode int = 200

/*GetAppCodesOK Successful Response

swagger:response getAppCodesOK
*/
type GetAppCodesOK struct {

	/*
	  In: Body
	*/
	Payload models.GetAppMessagesResponse `json:"body,omitempty"`
}

// NewGetAppCodesOKFunc is a type the create the response func
type NewGetAppCodesOKFunc func() *GetAppCodesOK

// NewGetAppCodesOK creates GetAppCodesOK with default headers values
func NewGetAppCodesOK() *GetAppCodesOK {

	return &GetAppCodesOK{}
}

// WithPayload adds the payload to the get app codes o k response
func (o *GetAppCodesOK) WithPayload(payload models.GetAppMessagesResponse) *GetAppCodesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get app codes o k response
func (o *GetAppCodesOK) SetPayload(payload models.GetAppMessagesResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAppCodesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.GetAppMessagesResponse{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		logrus.Panic(err) // let the recovery middleware deal with this
	}
}

// GetAppCodesInternalServerErrorCode is the HTTP code returned for type GetAppCodesInternalServerError
const GetAppCodesInternalServerErrorCode int = 500

/*GetAppCodesInternalServerError Internal Server Error

swagger:response getAppCodesInternalServerError
*/
type GetAppCodesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewGetAppCodesInternalServerErrorFunc is a type the create the response func
type NewGetAppCodesInternalServerErrorFunc func() *GetAppCodesInternalServerError

// NewGetAppCodesInternalServerError creates GetAppCodesInternalServerError with default headers values
func NewGetAppCodesInternalServerError() *GetAppCodesInternalServerError {

	return &GetAppCodesInternalServerError{}
}

// WithPayload adds the payload to the get app codes internal server error response
func (o *GetAppCodesInternalServerError) WithPayload(payload *models.ErrorMessage) *GetAppCodesInternalServerError {
	o.Payload = payload
	return o
}

// WithErr adds the Error payload with a default code to the get app codes internal server error response
func (o *GetAppCodesInternalServerError) FromErr(err error) *GetAppCodesInternalServerError {
	type swaggerErr interface {
		Plain() (code string, message string, attributes map[string]string)
	}

	if swaggerErr, ok := err.(swaggerErr); ok {
		code, message, attributes := swaggerErr.Plain()

		o.Payload = &models.ErrorMessage{
			Code:       code,
			Message:    message,
			Attributes: attributes,
		}
		return o
	}

	o.Payload = &models.ErrorMessage{
		Code:       "InternalServiceError",
		Message:    err.Error(),
		Attributes: nil,
	}

	return o
}

// WithError adds the Error payload to the get app codes internal server error response
func (o *GetAppCodesInternalServerError) FromMessage(gaemblaErr *vperror.AppMessage) *GetAppCodesInternalServerError {
	o.Payload = &models.ErrorMessage{
		Attributes: gaemblaErr.Attributes,
		Code:       gaemblaErr.Code,
		Message:    gaemblaErr.Message,
	}
	return o
}

// SetPayload sets the payload to the get app codes internal server error response
func (o *GetAppCodesInternalServerError) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAppCodesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			logrus.Panic(err) // let the recovery middleware deal with this
		}
	}
}
