// Code generated by go-swagger; DO NOT EDIT.

package general

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"encoding/json"
	"net/http"
	"runtime/debug"
	"time"

	"github.com/go-openapi/runtime/middleware"
	"github.com/lifebackend/vp/pkg/scope"
	prometheusmetrics "github.com/lifebackend/vp/tools/prometheus-metrics"
	"github.com/sirupsen/logrus"
)

func NewGetAppUpdateResponses() *GetAppUpdateResponses {
	return &GetAppUpdateResponses{
		GetAppUpdateOK:                  NewGetAppUpdateOK,
		GetAppUpdateInternalServerError: NewGetAppUpdateInternalServerError,
	}
}

type GetAppUpdateResponses struct {
	GetAppUpdateOK                  NewGetAppUpdateOKFunc
	GetAppUpdateInternalServerError NewGetAppUpdateInternalServerErrorFunc
}

// GetAppUpdateHandlerFunc turns a function with the right signature into a get app update handler
type GetAppUpdateHandlerFunc func(*GetAppUpdateParams, *GetAppUpdateResponses) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAppUpdateHandlerFunc) Handle(params *GetAppUpdateParams, respond *GetAppUpdateResponses) middleware.Responder {
	return fn(params, respond)
}

// GetAppUpdateHandler interface for that can handle valid get app update params
type GetAppUpdateHandler interface {
	Handle(*GetAppUpdateParams, *GetAppUpdateResponses) middleware.Responder
}

// NewGetAppUpdate creates a new http.Handler for the get app update operation
func NewGetAppUpdate(ctx *middleware.Context, handler GetAppUpdateHandler) *GetAppUpdate {
	return &GetAppUpdate{Context: ctx, Handler: handler}
}

/*GetAppUpdate swagger:route GET /app/update general getAppUpdate

GetAppUpdate get app update API

*/
type GetAppUpdate struct {
	Context *middleware.Context
	Handler GetAppUpdateHandler
}

func (o *GetAppUpdate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAppUpdateParams()

	if err := o.Context.BindValidRequest(r, route, Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	// pass predefined values from middleware
	requestCtx := r.Context()
	logger := requestCtx.Value("logger").(*logrus.Entry)
	xCorrelationID := requestCtx.Value("xCorrelationID").(string)

	// pass body
	Params.RequestBody = requestCtx.Value("body").([]byte)

	metrics := requestCtx.Value("metrics").(*prometheusmetrics.Metrics)

	// prepare scope
	Params.Scope = scope.NewScope(requestCtx, logger, xCorrelationID, metrics)
	Params.Scope.SetResource("GET /app/update")

	defer func() {
		if rec := recover(); rec != nil {
			Params.Scope.Logger().Errorf("%s: %s", rec, debug.Stack())

			xCorrelationID, ok := requestCtx.Value("xCorrelationID").(string)
			if ok {
				rw.Header().Add("X-Correlation-Id", xCorrelationID)
			}

			rw.WriteHeader(http.StatusInternalServerError)

			o.Context.Respond(rw, r, route.Produces, route, json.RawMessage([]byte(`{"code":"panic","message":""}`)))
		}
	}()

	responses := NewGetAppUpdateResponses()

	started := time.Now()

	res := o.Handler.Handle(Params, responses) // actually handle the request

	if metrics != nil {
		metrics.AddAPIResponseDuration("GET /app/update", time.Now().Sub(started))
	}

	o.Context.Respond(rw, r, route.Produces, route, res)

}
