// Code generated by go-swagger; DO NOT EDIT.

package general

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"encoding/json"
	"net/http"
	"runtime/debug"
	"time"

	"github.com/go-openapi/runtime/middleware"
	"github.com/lifebackend/vp/pkg/scope"
	prometheusmetrics "github.com/lifebackend/vp/tools/prometheus-metrics"
	"github.com/sirupsen/logrus"
)

func NewGetAppUpdateVersionResponses() *GetAppUpdateVersionResponses {
	return &GetAppUpdateVersionResponses{
		GetAppUpdateVersionOK:                  NewGetAppUpdateVersionOK,
		GetAppUpdateVersionInternalServerError: NewGetAppUpdateVersionInternalServerError,
	}
}

type GetAppUpdateVersionResponses struct {
	GetAppUpdateVersionOK                  NewGetAppUpdateVersionOKFunc
	GetAppUpdateVersionInternalServerError NewGetAppUpdateVersionInternalServerErrorFunc
}

// GetAppUpdateVersionHandlerFunc turns a function with the right signature into a get app update version handler
type GetAppUpdateVersionHandlerFunc func(*GetAppUpdateVersionParams, *GetAppUpdateVersionResponses) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAppUpdateVersionHandlerFunc) Handle(params *GetAppUpdateVersionParams, respond *GetAppUpdateVersionResponses) middleware.Responder {
	return fn(params, respond)
}

// GetAppUpdateVersionHandler interface for that can handle valid get app update version params
type GetAppUpdateVersionHandler interface {
	Handle(*GetAppUpdateVersionParams, *GetAppUpdateVersionResponses) middleware.Responder
}

// NewGetAppUpdateVersion creates a new http.Handler for the get app update version operation
func NewGetAppUpdateVersion(ctx *middleware.Context, handler GetAppUpdateVersionHandler) *GetAppUpdateVersion {
	return &GetAppUpdateVersion{Context: ctx, Handler: handler}
}

/*GetAppUpdateVersion swagger:route GET /app/update/{version} general getAppUpdateVersion

GetAppUpdateVersion get app update version API

*/
type GetAppUpdateVersion struct {
	Context *middleware.Context
	Handler GetAppUpdateVersionHandler
}

func (o *GetAppUpdateVersion) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAppUpdateVersionParams()

	if err := o.Context.BindValidRequest(r, route, Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	// pass predefined values from middleware
	requestCtx := r.Context()
	logger := requestCtx.Value("logger").(*logrus.Entry)
	xCorrelationID := requestCtx.Value("xCorrelationID").(string)

	// pass body
	Params.RequestBody = requestCtx.Value("body").([]byte)

	metrics := requestCtx.Value("metrics").(*prometheusmetrics.Metrics)

	// prepare scope
	Params.Scope = scope.NewScope(requestCtx, logger, xCorrelationID, metrics)
	Params.Scope.SetResource("GET /app/update/{version}")

	defer func() {
		if rec := recover(); rec != nil {
			Params.Scope.Logger().Errorf("%s: %s", rec, debug.Stack())

			xCorrelationID, ok := requestCtx.Value("xCorrelationID").(string)
			if ok {
				rw.Header().Add("X-Correlation-Id", xCorrelationID)
			}

			rw.WriteHeader(http.StatusInternalServerError)

			o.Context.Respond(rw, r, route.Produces, route, json.RawMessage([]byte(`{"code":"panic","message":""}`)))
		}
	}()

	responses := NewGetAppUpdateVersionResponses()

	started := time.Now()

	res := o.Handler.Handle(Params, responses) // actually handle the request

	if metrics != nil {
		metrics.AddAPIResponseDuration("GET /app/update/{version}", time.Now().Sub(started))
	}

	o.Context.Respond(rw, r, route.Produces, route, res)

}
