// Code generated by go-swagger; DO NOT EDIT.

package general

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/sirupsen/logrus"
)

// GetAppUpdateVersionURL generates an URL for the get app update version operation
type GetAppUpdateVersionURL struct {
	Version string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetAppUpdateVersionURL) WithBasePath(bp string) *GetAppUpdateVersionURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetAppUpdateVersionURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetAppUpdateVersionURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/app/update/{version}"

	version := o.Version
	if version != "" {
		_path = strings.Replace(_path, "{version}", version, -1)
	} else {
		return nil, errors.New("version is required on GetAppUpdateVersionURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetAppUpdateVersionURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		logrus.Panic(err)
	}
	if u == nil {
		logrus.Panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetAppUpdateVersionURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetAppUpdateVersionURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetAppUpdateVersionURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetAppUpdateVersionURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetAppUpdateVersionURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
