// Code generated by go-swagger; DO NOT EDIT.

package general

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"encoding/json"
	"net/http"
	"runtime/debug"
	"time"

	"github.com/go-openapi/runtime/middleware"
	"github.com/lifebackend/vp/pkg/scope"
	prometheusmetrics "github.com/lifebackend/vp/tools/prometheus-metrics"
	"github.com/sirupsen/logrus"
)

func NewPostProxyMessageResponses() *PostProxyMessageResponses {
	return &PostProxyMessageResponses{
		PostProxyMessageOK:                  NewPostProxyMessageOK,
		PostProxyMessageBadRequest:          NewPostProxyMessageBadRequest,
		PostProxyMessageInternalServerError: NewPostProxyMessageInternalServerError,
	}
}

type PostProxyMessageResponses struct {
	PostProxyMessageOK                  NewPostProxyMessageOKFunc
	PostProxyMessageBadRequest          NewPostProxyMessageBadRequestFunc
	PostProxyMessageInternalServerError NewPostProxyMessageInternalServerErrorFunc
}

// PostProxyMessageHandlerFunc turns a function with the right signature into a post proxy message handler
type PostProxyMessageHandlerFunc func(*PostProxyMessageParams, *PostProxyMessageResponses) middleware.Responder

// Handle executing the request and returning a response
func (fn PostProxyMessageHandlerFunc) Handle(params *PostProxyMessageParams, respond *PostProxyMessageResponses) middleware.Responder {
	return fn(params, respond)
}

// PostProxyMessageHandler interface for that can handle valid post proxy message params
type PostProxyMessageHandler interface {
	Handle(*PostProxyMessageParams, *PostProxyMessageResponses) middleware.Responder
}

// NewPostProxyMessage creates a new http.Handler for the post proxy message operation
func NewPostProxyMessage(ctx *middleware.Context, handler PostProxyMessageHandler) *PostProxyMessage {
	return &PostProxyMessage{Context: ctx, Handler: handler}
}

/*PostProxyMessage swagger:route POST /proxy/message general postProxyMessage

PostProxyMessage post proxy message API

*/
type PostProxyMessage struct {
	Context *middleware.Context
	Handler PostProxyMessageHandler
}

func (o *PostProxyMessage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostProxyMessageParams()

	if err := o.Context.BindValidRequest(r, route, Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	// pass predefined values from middleware
	requestCtx := r.Context()
	logger := requestCtx.Value("logger").(*logrus.Entry)
	xCorrelationID := requestCtx.Value("xCorrelationID").(string)

	// pass body
	Params.RequestBody = requestCtx.Value("body").([]byte)

	metrics := requestCtx.Value("metrics").(*prometheusmetrics.Metrics)

	// prepare scope
	Params.Scope = scope.NewScope(requestCtx, logger, xCorrelationID, metrics)
	Params.Scope.SetResource("POST /proxy/message")

	defer func() {
		if rec := recover(); rec != nil {
			Params.Scope.Logger().Errorf("%s: %s", rec, debug.Stack())

			xCorrelationID, ok := requestCtx.Value("xCorrelationID").(string)
			if ok {
				rw.Header().Add("X-Correlation-Id", xCorrelationID)
			}

			rw.WriteHeader(http.StatusInternalServerError)

			o.Context.Respond(rw, r, route.Produces, route, json.RawMessage([]byte(`{"code":"panic","message":""}`)))
		}
	}()

	responses := NewPostProxyMessageResponses()

	started := time.Now()

	res := o.Handler.Handle(Params, responses) // actually handle the request

	if metrics != nil {
		metrics.AddAPIResponseDuration("POST /proxy/message", time.Now().Sub(started))
	}

	o.Context.Respond(rw, r, route.Produces, route, res)

}
