// Code generated by go-swagger; DO NOT EDIT.

package general

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/lifebackend/vp/internal/vperror"
	"github.com/sirupsen/logrus"

	"github.com/lifebackend/vp/internal/app/vp/server/models"
)

// PostPushOKCode is the HTTP code returned for type PostPushOK
const PostPushOKCode int = 200

/*
PostPushOK Successful Response

swagger:response postPushOK
*/
type PostPushOK struct {

	/*
	  In: Body
	*/
	Payload *models.PostMessageResponse `json:"body,omitempty"`
}

// NewPostPushOKFunc is a type the create the response func
type NewPostPushOKFunc func() *PostPushOK

// NewPostPushOK creates PostPushOK with default headers values
func NewPostPushOK() *PostPushOK {

	return &PostPushOK{}
}

// WithPayload adds the payload to the post push o k response
func (o *PostPushOK) WithPayload(payload *models.PostMessageResponse) *PostPushOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post push o k response
func (o *PostPushOK) SetPayload(payload *models.PostMessageResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPushOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			logrus.Panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostPushInternalServerErrorCode is the HTTP code returned for type PostPushInternalServerError
const PostPushInternalServerErrorCode int = 500

/*
PostPushInternalServerError Internal Server Error

swagger:response postPushInternalServerError
*/
type PostPushInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorMessage `json:"body,omitempty"`
}

// NewPostPushInternalServerErrorFunc is a type the create the response func
type NewPostPushInternalServerErrorFunc func() *PostPushInternalServerError

// NewPostPushInternalServerError creates PostPushInternalServerError with default headers values
func NewPostPushInternalServerError() *PostPushInternalServerError {

	return &PostPushInternalServerError{}
}

// WithPayload adds the payload to the post push internal server error response
func (o *PostPushInternalServerError) WithPayload(payload *models.ErrorMessage) *PostPushInternalServerError {
	o.Payload = payload
	return o
}

// WithErr adds the Error payload with a default code to the post push internal server error response
func (o *PostPushInternalServerError) FromErr(err error) *PostPushInternalServerError {
	type swaggerErr interface {
		Plain() (code string, message string, attributes map[string]string)
	}

	if swaggerErr, ok := err.(swaggerErr); ok {
		code, message, attributes := swaggerErr.Plain()

		o.Payload = &models.ErrorMessage{
			Code:       code,
			Message:    message,
			Attributes: attributes,
		}
		return o
	}

	o.Payload = &models.ErrorMessage{
		Code:       "InternalServiceError",
		Message:    err.Error(),
		Attributes: nil,
	}

	return o
}

// WithError adds the Error payload to the post push internal server error response
func (o *PostPushInternalServerError) FromMessage(gaemblaErr *vperror.AppMessage) *PostPushInternalServerError {
	o.Payload = &models.ErrorMessage{
		Attributes: gaemblaErr.Attributes,
		Code:       gaemblaErr.Code,
		Message:    gaemblaErr.Message,
	}
	return o
}

// SetPayload sets the payload to the post push internal server error response
func (o *PostPushInternalServerError) SetPayload(payload *models.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPushInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			logrus.Panic(err) // let the recovery middleware deal with this
		}
	}
}
