// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Wallet API
//
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /
//  Version: 0.1.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - text/html
//    - application/json
//
// swagger:meta
package restapi
