// Code generated by go-swagger; DO NOT EDIT.

package general

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"encoding/json"
	"net/http"
	"runtime/debug"
	"time"

	"github.com/go-openapi/runtime/middleware"
	"github.com/nvsco/wallet/pkg/scope"
	prometheusmetrics "github.com/nvsco/wallet/tools/prometheus-metrics"
	"github.com/sirupsen/logrus"
)

func NewGetAppCodesResponses() *GetAppCodesResponses {
	return &GetAppCodesResponses{
		GetAppCodesOK:                  NewGetAppCodesOK,
		GetAppCodesInternalServerError: NewGetAppCodesInternalServerError,
	}
}

type GetAppCodesResponses struct {
	GetAppCodesOK                  NewGetAppCodesOKFunc
	GetAppCodesInternalServerError NewGetAppCodesInternalServerErrorFunc
}

// GetAppCodesHandlerFunc turns a function with the right signature into a get app codes handler
type GetAppCodesHandlerFunc func(*GetAppCodesParams, *GetAppCodesResponses) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAppCodesHandlerFunc) Handle(params *GetAppCodesParams, respond *GetAppCodesResponses) middleware.Responder {
	return fn(params, respond)
}

// GetAppCodesHandler interface for that can handle valid get app codes params
type GetAppCodesHandler interface {
	Handle(*GetAppCodesParams, *GetAppCodesResponses) middleware.Responder
}

// NewGetAppCodes creates a new http.Handler for the get app codes operation
func NewGetAppCodes(ctx *middleware.Context, handler GetAppCodesHandler) *GetAppCodes {
	return &GetAppCodes{Context: ctx, Handler: handler}
}

/*GetAppCodes swagger:route GET /app-codes general getAppCodes

Get List of Application Codes

Get list of application codes

*/
type GetAppCodes struct {
	Context *middleware.Context
	Handler GetAppCodesHandler
}

func (o *GetAppCodes) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAppCodesParams()

	if err := o.Context.BindValidRequest(r, route, Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	// pass predefined values from middleware
	requestCtx := r.Context()
	logger := requestCtx.Value("logger").(*logrus.Entry)
	xCorrelationID := requestCtx.Value("xCorrelationID").(string)

	// pass body
	Params.RequestBody = requestCtx.Value("body").([]byte)

	metrics := requestCtx.Value("metrics").(*prometheusmetrics.Metrics)

	// prepare scope
	Params.Scope = scope.NewScope(requestCtx, logger, xCorrelationID, metrics)
	Params.Scope.SetResource("GET /app-codes")

	defer func() {
		if rec := recover(); rec != nil {
			Params.Scope.Logger().Errorf("%s: %s", rec, debug.Stack())

			xCorrelationID, ok := requestCtx.Value("xCorrelationID").(string)
			if ok {
				rw.Header().Add("X-Correlation-Id", xCorrelationID)
			}

			rw.WriteHeader(http.StatusInternalServerError)

			o.Context.Respond(rw, r, route.Produces, route, json.RawMessage([]byte(`{"code":"panic","message":""}`)))
		}
	}()

	responses := NewGetAppCodesResponses()

	started := time.Now()

	res := o.Handler.Handle(Params, responses) // actually handle the request

	if metrics != nil {
		metrics.AddAPIResponseDuration("GET /app-codes", time.Now().Sub(started))
	}

	o.Context.Respond(rw, r, route.Produces, route, res)

}
