//	Do not edit this file. This file was auto generated
//	All the changes will be overwritten by the "make generate-handler-declarations" command

package handlers

import (
	"github.com/lifebackend/vp/internal/app/vp/server/restapi/operations"
	"github.com/lifebackend/vp/internal/app/vp/server/restapi/operations/general"
	"github.com/lifebackend/vp/internal/app/vp/server/restapi/operations/health"
)

func AddDefaultHandlers(api *operations.VpAPI, h *Handlers) {
	// default handle functions
	api.GeneralGetAppUpdateHandler = general.GetAppUpdateHandlerFunc(h.GeneralGetAppUpdateHandler)
	api.GeneralPostPingHandler = general.PostPingHandlerFunc(h.GeneralPostPingHandler)
	api.GeneralPostPushHandler = general.PostPushHandlerFunc(h.GeneralPostPushHandler)
	api.GeneralPostSmsHandler = general.PostSmsHandlerFunc(h.GeneralPostSmsHandler)
	api.GeneralGetAppCodesHandler = general.GetAppCodesHandlerFunc(h.GeneralGetAppCodesHandler)
	api.HealthGetLivenessProbeHandler = health.GetLivenessProbeHandlerFunc(h.HealthGetLivenessProbeHandler)
	api.HealthGetReadinessProbeHandler = health.GetReadinessProbeHandlerFunc(h.HealthGetReadinessProbeHandler)

}
