// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"encoding/json"
	"net/http"
	"runtime/debug"
	"time"

	"github.com/go-openapi/runtime/middleware"
	"github.com/nvsco/wallet/pkg/scope"
	prometheusmetrics "github.com/nvsco/wallet/tools/prometheus-metrics"
	"github.com/sirupsen/logrus"
)

func NewGetReadinessProbeResponses() *GetReadinessProbeResponses {
	return &GetReadinessProbeResponses{
		GetReadinessProbeOK:                  NewGetReadinessProbeOK,
		GetReadinessProbeInternalServerError: NewGetReadinessProbeInternalServerError,
	}
}

type GetReadinessProbeResponses struct {
	GetReadinessProbeOK                  NewGetReadinessProbeOKFunc
	GetReadinessProbeInternalServerError NewGetReadinessProbeInternalServerErrorFunc
}

// GetReadinessProbeHandlerFunc turns a function with the right signature into a get readiness probe handler
type GetReadinessProbeHandlerFunc func(*GetReadinessProbeParams, *GetReadinessProbeResponses) middleware.Responder

// Handle executing the request and returning a response
func (fn GetReadinessProbeHandlerFunc) Handle(params *GetReadinessProbeParams, respond *GetReadinessProbeResponses) middleware.Responder {
	return fn(params, respond)
}

// GetReadinessProbeHandler interface for that can handle valid get readiness probe params
type GetReadinessProbeHandler interface {
	Handle(*GetReadinessProbeParams, *GetReadinessProbeResponses) middleware.Responder
}

// NewGetReadinessProbe creates a new http.Handler for the get readiness probe operation
func NewGetReadinessProbe(ctx *middleware.Context, handler GetReadinessProbeHandler) *GetReadinessProbe {
	return &GetReadinessProbe{Context: ctx, Handler: handler}
}

/*GetReadinessProbe swagger:route GET /_readinessProbe health getReadinessProbe

Readiness Probe

Readiness Probe

*/
type GetReadinessProbe struct {
	Context *middleware.Context
	Handler GetReadinessProbeHandler
}

func (o *GetReadinessProbe) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetReadinessProbeParams()

	if err := o.Context.BindValidRequest(r, route, Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	// pass predefined values from middleware
	requestCtx := r.Context()
	logger := requestCtx.Value("logger").(*logrus.Entry)
	xCorrelationID := requestCtx.Value("xCorrelationID").(string)

	// pass body
	Params.RequestBody = requestCtx.Value("body").([]byte)

	metrics := requestCtx.Value("metrics").(*prometheusmetrics.Metrics)

	// prepare scope
	Params.Scope = scope.NewScope(requestCtx, logger, xCorrelationID, metrics)
	Params.Scope.SetResource("GET /_readinessProbe")

	defer func() {
		if rec := recover(); rec != nil {
			Params.Scope.Logger().Errorf("%s: %s", rec, debug.Stack())

			xCorrelationID, ok := requestCtx.Value("xCorrelationID").(string)
			if ok {
				rw.Header().Add("X-Correlation-Id", xCorrelationID)
			}

			rw.WriteHeader(http.StatusInternalServerError)

			o.Context.Respond(rw, r, route.Produces, route, json.RawMessage([]byte(`{"code":"panic","message":""}`)))
		}
	}()

	responses := NewGetReadinessProbeResponses()

	started := time.Now()

	res := o.Handler.Handle(Params, responses) // actually handle the request

	if metrics != nil {
		metrics.AddAPIResponseDuration("GET /_readinessProbe", time.Now().Sub(started))
	}

	o.Context.Respond(rw, r, route.Produces, route, res)

}
