swagger: "2.0"
info:
  version: 0.1.0
  title: VP API
consumes:
  - application/json
produces:
  - application/json
  - text/html
schemes:
  - http
  - https
paths:
  /_livenessProbe:
    get:
      tags:
        - health
      summary: Liveness Probe
      description: Liveness Probe
      operationId: getLivenessProbe
      produces:
        - application/json
      responses:
        200:
          description: Successful Response
          schema:
            $ref: "#/definitions/LivenessProbe"
        500:
          description: Internal Server Error
  /_readinessProbe:
    get:
      tags:
        - health
      summary: Readiness Probe
      description: Readiness Probe
      operationId: getReadinessProbe
      produces:
        - application/json
      responses:
        200:
          description: Successful Response
        500:
          description: Internal Server Error
  /ping:
    post:
      tags:
        - general
      produces:
        - application/json
      responses:
        200:
          description: Successful Response
          schema:
            $ref: "#/definitions/PostPingResponse"
        500:
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorMessage"
  /sms:
    post:
      tags:
        - general
      produces:
        - application/json
      responses:
        200:
          description: Successful Response
          schema:
            $ref: "#/definitions/GetAppMessagesResponse"
        500:
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorMessage"

  /push:
    post:
      tags:
        - general
      produces:
        - application/json
      responses:
        200:
          description: Successful Response
          schema:
            $ref: "#/definitions/PostMessageResponse"
        500:
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorMessage"

  /app/update:
    get:
      tags:
        - general
      produces:
        - application/octet-stream
      responses:
        200:
          description: Successful Response
          schema:
            type: string
            format: binary
        500:
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorMessage"
  /app-codes:
    get:
      tags:
        - general
      summary: Get List of Application Codes
      description: Get list of application codes
      operationId: getAppCodes
      produces:
        - application/json
      responses:
        200:
          description: Successful Response
          schema:
            $ref: "#/definitions/GetAppMessagesResponse"
        500:
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ErrorMessage"
definitions:
  AppMessage:
    title: AppMessage
    type: object
    required:
      - message
      - code
      - attributes
    properties:
      code:
        title: Code
        type: string
        x-nullable: false
      message:
        title: Message
        type: string
        x-nullable: false
      attributes:
        description: attributes
        type: array
        items:
          type: string
        x-nullable: false
  PingMessage:
    title: PingMessage
    type: object
    required:
      - id
      - password
    properties:
      id:
        title: ID
        type: string
        x-nullable: false
      password:
        title: password
        type: string
        x-nullable: false
  SuccessResponse:
    title: PingResponse
    type: object
    required:
      - success
    properties:
      success:
        title: Success
        type: boolean
        x-nullable: false
  MessageRequest:
    title: MessageResponse
    type: object
    required:
      - from
      - message
      - datetime
      - password
    properties:
      from:
        title: From
        type: string
        x-nullable: false
      message:
        title: Message
        type: string
        x-nullable: false
      datetime:
        title: Date
        type: number
        x-nullable: false
      password:
        title: password
        type: string
        x-nullable: false

  GetAppMessagesResponse:
    title: GetAppCodesResponse
    type: array
    items:
      $ref: "#/definitions/AppMessage"
  PostMessageRequest:
    title: PostMessageRequest
    type: object
    $ref: "#/definitions/MessageRequest"
  PostMessageResponse:
    title: PostMessageResponse
    type: object
    $ref: "#/definitions/MessageRequest"
  PostPingResponse:
    title: PostPingResponse
    type: object
    $ref: "#/definitions/SuccessResponse"
  ErrorMessage:
    title: ErrorMessage
    required:
      - message
    type: object
    properties:
      code:
        title: Code
        type: string
        x-nullable: false
      message:
        title: Message
        type: string
        x-nullable: false
      attributes:
        description: attributes
        type: object
        additionalProperties:
          type: string
        x-nullable: false
  LivenessProbe:
    title: LivenessProbe
    required:
      - tag
    type: object
    properties:
      tag:
        title: Tag
        type: string
        x-nullable: false
      components:
        title: LivenessProbeComponents
        type: array
        items:
          $ref: "#/definitions/LivenessProbeComponent"
  LivenessProbeComponent:
    title: LivenessProbeComponent
    required:
      - name
      - status
    type: object
    properties:
      name:
        title: Name
        type: string
        x-nullable: false
      status:
        title: Status
        type: boolean
        x-nullable: false


